language: java


addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

services:
  - postgresql

before_script:
  - psql -f $TRAVIS_BUILD_DIR/server/core/src/main/resources/create_schema.sql -U postgres

script:
  - mvn clean test
